# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NginxPrometheusExporter < Formula
  desc "NGINX Prometheus Exporter for NGINX and NGINX Plus"
  homepage "https://website"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lucacome/nginx-prometheus-exporter/releases/download/v0.9.0/nginx-prometheus-exporter_0.9.0_darwin_arm64.tar.gz"
      sha256 "98618673d45eaf250dc5690d458dfcf02144e8e9ad8a6ba64eb9c3629d773e12"

      def install
        bin.install "nginx-prometheus-exporter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucacome/nginx-prometheus-exporter/releases/download/v0.9.0/nginx-prometheus-exporter_0.9.0_darwin_amd64.tar.gz"
      sha256 "a73a0e7f3d9186f219d2b0593bf9197dd6ca27742d59c0ba6d75dabcf3a1af5f"

      def install
        bin.install "nginx-prometheus-exporter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lucacome/nginx-prometheus-exporter/releases/download/v0.9.0/nginx-prometheus-exporter_0.9.0_linux_armv6.tar.gz"
      sha256 "fc4e34ce6e649702dbf8dcdcbc96bd27bc1caf84b321b1f30376ddfe7a3dd5a2"

      def install
        bin.install "nginx-prometheus-exporter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucacome/nginx-prometheus-exporter/releases/download/v0.9.0/nginx-prometheus-exporter_0.9.0_linux_arm64.tar.gz"
      sha256 "6effa7a0d11cadbfb49c663ff53fd8f6c6318deb096b06489882e60982438da3"

      def install
        bin.install "nginx-prometheus-exporter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lucacome/nginx-prometheus-exporter/releases/download/v0.9.0/nginx-prometheus-exporter_0.9.0_linux_amd64.tar.gz"
      sha256 "156986f44c9b5003f0cf3a053c5e6746aa21879407f658d4cf972bcc4b601a6d"

      def install
        bin.install "nginx-prometheus-exporter"
      end
    end
  end

  test do
    system "#{bin}/nginx-prometheus-exporter -version"
  end
end
